### ISSUE TITLE
prefix 'siren' to all siren related annotation?

### ISSUE THREAD

**Issue by shingo-kumagai** [shingo-kumagai/BEAR.SirenModule#3]

**Comment by koriym** [comment]
+1

Prefix `@Siren`  makes sense when same name is required in another hypermedia format,
Also it's handy when we type `@Siren`, then autocomplete shows the candidate.

**Comment by shingo-kumagai** [comment]
That make sense to me too and i will reflect it!
Thank you for your HELP! :)
